"""
tools/test_gmail_mcp.py

Self-contained test script for the Gmail MCP tool wrapper.
Run with:  python tools/test_gmail_mcp.py

No pytest required — plain runnable Python.
Tests run in order; live-send tests require TEST_EMAIL env var.
"""

import os
import sys
from dotenv import load_dotenv

# Allow running from repo root: python tools/test_gmail_mcp.py
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

from tools.gmail_mcp import (
    check_gmail_mcp_health,
    send_deal_alert,
    send_ic_memo,
)

passed = 0
total = 7


def report(test_num: int, name: str, ok: bool, detail: str = "") -> None:
    global passed
    status = "PASS" if ok else "FAIL"
    suffix = f" — {detail}" if detail else ""
    print(f"  [{status}] TEST {test_num}: {name}{suffix}")
    if ok:
        passed += 1


# ─────────────────────────────────────────────────────────────────────────────
print("\n=== DealBrain Gmail MCP — Tool Tests ===\n")

# TEST 1 — Health check
result = check_gmail_mcp_health()
ok = result.get("healthy") is True
report(1, "Health check", ok, "" if ok else str(result))

# TEST 2 — Input validation: empty recipient
result = send_ic_memo(to="", subject="Test", html_body="<p>Test</p>")
ok = result.get("success") is False and "Invalid recipient" in result.get("error", "")
report(2, "Empty recipient rejected", ok, "" if ok else str(result))

# TEST 3 — Input validation: invalid email format (no @)
result = send_ic_memo(to="not-an-email", subject="Test", html_body="<p>Test</p>")
ok = result.get("success") is False
report(3, "Invalid email format rejected", ok, "" if ok else str(result))

# TEST 4 — Input validation: empty html_body
result = send_ic_memo(to="test@example.com", subject="Test", html_body="")
ok = result.get("success") is False and "html_body" in result.get("error", "")
report(4, "Empty html_body rejected", ok, "" if ok else str(result))

# TEST 5 — Input validation: empty subject
result = send_ic_memo(to="test@example.com", subject="", html_body="<p>hi</p>")
ok = result.get("success") is False
report(5, "Empty subject rejected", ok, "" if ok else str(result))

# TEST 6 — Real send (requires TEST_EMAIL env var)
to_email = os.getenv("TEST_EMAIL")
if not to_email:
    print("  [SKIP] TEST 6: Real IC memo send — set TEST_EMAIL env var to run")
    total -= 1  # don't count skipped tests against total
else:
    ic_memo_html = """
<html>
<body style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto;padding:20px">
  <h1 style="color:#1a1a2e;border-bottom:3px solid #e74c3c;padding-bottom:10px">
    IC MEMO — AcmeCo Series B (CONFIDENTIAL)
  </h1>

  <h2 style="color:#2c3e50">Executive Summary</h2>
  <p>AcmeCo is a B2B SaaS platform targeting mid-market logistics operators.
     ARR of €4.2M growing at 110% YoY. Seeking €12M Series B at a €48M pre-money
     valuation. Management team has two prior successful exits.</p>

  <h2 style="color:#2c3e50">Risk Flags</h2>
  <table style="width:100%;border-collapse:collapse;font-size:14px">
    <thead>
      <tr style="background:#e74c3c;color:#fff">
        <th style="padding:10px;text-align:left">Risk</th>
        <th style="padding:10px;text-align:left">Severity</th>
        <th style="padding:10px;text-align:left">Mitigation</th>
      </tr>
    </thead>
    <tbody>
      <tr style="background:#fdf2f2">
        <td style="padding:10px;border:1px solid #f0d0d0">Customer concentration — top 3 clients = 61% ARR</td>
        <td style="padding:10px;border:1px solid #f0d0d0;color:#c0392b"><strong>HIGH</strong></td>
        <td style="padding:10px;border:1px solid #f0d0d0">Pipeline shows 14 new enterprise prospects; churn covenant proposed</td>
      </tr>
      <tr>
        <td style="padding:10px;border:1px solid #e0e0e0">Regulatory exposure in 3 EU jurisdictions post-DMA</td>
        <td style="padding:10px;border:1px solid #e0e0e0;color:#e67e22"><strong>MEDIUM</strong></td>
        <td style="padding:10px;border:1px solid #e0e0e0">External counsel retained; compliance budget ring-fenced in cap table</td>
      </tr>
    </tbody>
  </table>

  <p style="font-size:11px;color:#999;margin-top:24px">
    Generated by DealBrain · Powered by Gemini 2.0 Flash on GCP · CONFIDENTIAL
  </p>
</body>
</html>
"""
    result = send_ic_memo(
        to=to_email,
        subject="IC Memo — AcmeCo Series B (CONFIDENTIAL) [TEST]",
        html_body=ic_memo_html,
        cc=[],
        sender_name="DealBrain Test",
    )
    ok = result.get("success") is True
    report(6, "Real IC memo send", ok, "" if ok else str(result))

# TEST 7 — send_deal_alert (requires TEST_EMAIL env var)
to_email = os.getenv("TEST_EMAIL")
if not to_email:
    print("  [SKIP] TEST 7: Real deal alert send — set TEST_EMAIL env var to run")
    total -= 1  # don't count skipped tests against total
else:
    result = send_deal_alert(
        to=to_email,
        deal_name="AcmeCo GmbH",
        alert_type="RISK_FLAG",
        message=(
            "Pension deficit of €14M identified in audited accounts. "
            "Requires valuation adjustment before IC submission."
        ),
        cc=[],
    )
    ok = result.get("success") is True
    report(7, "send_deal_alert RISK_FLAG", ok, "" if ok else str(result))

# ─────────────────────────────────────────────────────────────────────────────
print(f"\n{'='*40}")
print(f"  {passed}/{total} tests passed")
print(f"{'='*40}\n")

sys.exit(0 if passed == total else 1)
